export declare function line_iterator_(
	readable_stream_or_reader:line_iterator__readable_reader_T,
	text_decoder?:TextDecoder
):Iterable<string>
export type line_iterator__readable_reader_T = ReadableStream|ReadableStreamDefaultReader|ReadableStreamBYOBReader
